replicas: 1
image:
  repository: confluentinc/cp-kafka-connect
  tag: "7.6.0"
  pullPolicy: IfNotPresent
resources: {}
persistence:
  plugins:
    enabled: true
    size: 1Gi
    storageClass: standard
  buffer:
    enabled: true
    size: 1Gi
    storageClass: standard
service:
  type: ClusterIP
  port: 8083
env: {}
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
podSecurityContext:
  fsGroup: 1001
securityContext:
  runAsUser: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
monitoring:
  enabled: false


