apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: sellio-infra
  labels:
    app.kubernetes.io/name: kafka
spec:
  serviceName: kafka
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      topologySpreadConstraints:
        {{- toYaml .Values.topologySpreadConstraints | nindent 8 }}
      containers:
        - name: redpanda
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          args:
            - redpanda
            - start
            - --check=false
            - --overprovisioned
            - --smp=1
            - --memory=512M
            - --reserve-memory=0M
            - --node-id=0
            - --kafka-addr=PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr=PLAINTEXT://kafka.sellio-infra.svc.cluster.local:9092
            - --rpc-addr=0.0.0.0:33145
            - --advertise-rpc-addr=kafka.sellio-infra.svc.cluster.local:33145
            - --mode=dev-container
          ports:
            - name: kafka
              containerPort: 9092
            - name: admin
              containerPort: 9644
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/redpanda/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.storageClass | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.size | quote }}


