replicas: 1
image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.12.0"
  pullPolicy: IfNotPresent
resources: {}
persistence:
  enabled: true
  size: 10Gi
  storageClass: standard
service:
  client:
    type: ClusterIP
    port: 9200
extraEnvs: []
nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
podSecurityContext:
  fsGroup: 1000
securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  allowPrivilegeEscalation: false
monitoring:
  enabled: false


