replicas: 1
image:
  repository: confluentinc/cp-kafka-connect
  tag: "7.6.0"
resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "800m"
    memory: "1Gi"
persistence:
  plugins:
    size: 1Gi
    storageClass: standard
  buffer:
    size: 1Gi
    storageClass: standard
service:
  type: NodePort
  port: 8083
env:
  CONNECT_BOOTSTRAP_SERVERS: "kafka:9092"
  CONNECT_GROUP_ID: "sellio-connect"
  CONNECT_CONFIG_STORAGE_TOPIC: "__connect_configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "__connect_offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "__connect_status"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: "false"
  CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/java/plugins"
  CONNECT_LISTENERS: "http://0.0.0.0:8083"
  CONNECT_REST_PORT: "8083"
  CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect.sellio-infra.svc.cluster.local"
  CUB_CLASSPATH: "/usr/share/java/kafka/*:/usr/share/java/cp-base-new/*"
  KAFKA_HEAP_OPTS: "-Xms128M -Xmx512M"
monitoring:
  enabled: false


