cluster:
  enabled: true
  nodes: 3
persistence:
  size: 5Gi
  storageClass: standard
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "300m"
    memory: "256Mi"
monitoring:
  enabled: false


