apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: elasticsearch-pdb
  namespace: sellio-data
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elasticsearch


