apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: sellio-infra
  labels:
    app.kubernetes.io/name: elasticsearch
spec:
  type: {{ .Values.service.client.type }}
  ports:
    - name: http
      port: {{ .Values.service.client.port }}
      targetPort: 9200
  selector:
    app.kubernetes.io/name: elasticsearch


