{{- $initEnabled := true -}}
{{- with .Values.initdb -}}
{{-   $initEnabled = (default true .enabled) -}}
{{- end -}}
{{- if $initEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-app-users
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- $existing := (lookup "v1" "Secret" .Release.Namespace "postgresql-app-users") }}
data:
  user-main-password: {{ default (randAlphaNum 24 | b64enc) (and $existing (index $existing.data "user-main-password")) }}
  user-cart-password: {{ default (randAlphaNum 24 | b64enc) (and $existing (index $existing.data "user-cart-password")) }}
  user-notifications-password: {{ default (randAlphaNum 24 | b64enc) (and $existing (index $existing.data "user-notifications-password")) }}
{{- end }}


