# Сервіси для primary та read-only кінцевих точок
apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary
  namespace: sellio-infra
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: {{ .Values.service.primary.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.primary.port }}
      targetPort: 5432
      {{- if eq .Values.service.primary.type "NodePort" }}
      nodePort: 30432
      {{- end }}
  selector:
    app.kubernetes.io/name: postgresql
    role: primary
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-read
  namespace: sellio-infra
  labels:
    app.kubernetes.io/name: postgresql
spec:
  type: {{ .Values.service.read.type }}
  ports:
    - name: postgres
      port: {{ .Values.service.read.port }}
      targetPort: 5432
      {{- if eq .Values.service.read.type "NodePort" }}
      nodePort: 30433
      {{- end }}
  selector:
    app.kubernetes.io/name: postgresql
    role: read


