apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kafka-connect
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    - host: kafka-connect.sellio.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-connect
                port:
                  number: 8083


