apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: sellio-infra
  labels:
    app.kubernetes.io/name: kafka-connect
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8083
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: 30883
      {{- end }}
  selector:
    app.kubernetes.io/name: kafka-connect


